(() => {
  'use strict';

  const STATUS_LABELS = { pending_confirmation: 'Menunggu konfirmasi', confirmed: 'Dikonfirmasi', paid: 'Dibayar', processing: 'Diproses', shipped: 'Dikirim', completed: 'Selesai', cancelled: 'Dibatalkan' };
  const state = { csrfToken: '', currentUser: null, activeView: 'dashboard', products: [], orders: [], users: [], statuses: [], productQuery: '', orderQuery: '', orderStatus: 'all', userQuery: '', editingProductId: null, editingUserId: null, selectedOrderId: null, pendingImage: null };
  const $ = (selector) => document.querySelector(selector);
  const elements = {
    loginView: $('[data-login-view]'), loginForm: $('[data-login-form]'), loginMessage: $('[data-login-message]'), dashboard: $('[data-dashboard]'),
    productList: $('[data-product-list]'), productTemplate: $('#admin-product-template'), productCount: $('[data-product-count]'), productSearch: $('[data-admin-search]'), productEmpty: $('[data-admin-empty]'),
    editor: $('[data-editor-dialog]'), editorTitle: $('[data-editor-title]'), productForm: $('[data-product-form]'), editorMessage: $('[data-editor-message]'), imageFile: $('[data-image-file]'), imagePreview: $('[data-image-preview]'),
    orderList: $('[data-order-list]'), orderTemplate: $('#order-row-template'), orderCount: $('[data-order-count]'), orderSearch: $('[data-order-search]'), orderFilter: $('[data-order-status-filter]'), orderEmpty: $('[data-order-empty]'), orderDialog: $('[data-order-dialog]'), orderStatusForm: $('[data-order-status-form]'),
    userList: $('[data-user-list]'), userTemplate: $('#user-row-template'), userCount: $('[data-user-count]'), userSearch: $('[data-user-search]'), userEmpty: $('[data-user-empty]'), userDialog: $('[data-user-dialog]'), userForm: $('[data-user-form]'), userMessage: $('[data-user-message]'),
    toast: $('[data-admin-toast]')
  };

  async function request(url, options = {}) {
    const method = options.method || 'GET'; const headers = { ...(options.headers || {}) };
    if (options.body && !headers['Content-Type']) headers['Content-Type'] = 'application/json';
    if (!['GET', 'HEAD'].includes(method) && url !== '/api/admin/login') headers['X-CSRF-Token'] = state.csrfToken;
    const response = await fetch(url, { ...options, method, headers, credentials: 'same-origin' });
    let payload = {}; try { payload = await response.json(); } catch { payload = {}; }
    if (!response.ok) { if (response.status === 401 && url !== '/api/admin/login') showLogin('Sesi Anda berakhir. Silakan masuk kembali.'); const error = new Error([payload.error, ...(payload.details || [])].filter(Boolean).join(' ') || 'Permintaan gagal.'); error.status = response.status; throw error; }
    return payload;
  }

  function showLogin(message = '') { elements.loginView.hidden = false; elements.dashboard.hidden = true; elements.loginMessage.hidden = !message; elements.loginMessage.textContent = message; state.csrfToken = ''; state.currentUser = null; }
  function showDashboard(user) { state.currentUser = user; elements.loginView.hidden = true; elements.dashboard.hidden = false; $('[data-admin-user]').textContent = `${user.name || user.username} · ${user.role}`; $('[data-users-nav]').hidden = !['owner', 'admin'].includes(user.role); }
  function formatMoney(value) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0); }
  function formatDate(value, withTime = true) { if (!value) return '—'; return new Intl.DateTimeFormat('id-ID', withTime ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }).format(new Date(value)); }
  function statusLabel(status) { return STATUS_LABELS[status] || String(status).replaceAll('_', ' '); }
  function setDialog(open, dialog) { if (open) { dialog.showModal(); document.body.classList.add('dialog-open'); } else { dialog.close(); if (!$('dialog[open]')) document.body.classList.remove('dialog-open'); } }

  async function switchView(name) {
    if (name === 'users' && !['owner', 'admin'].includes(state.currentUser?.role)) return;
    state.activeView = name;
    document.querySelectorAll('[data-view]').forEach((view) => { view.hidden = view.dataset.view !== name; });
    document.querySelectorAll('[data-view-button]').forEach((button) => button.setAttribute('aria-pressed', String(button.dataset.viewButton === name)));
    if (name === 'dashboard') await loadDashboard();
    if (name === 'orders') await loadOrders();
    if (name === 'products') await loadProducts();
    if (name === 'users') await loadUsers();
  }

  async function loadDashboard() { const payload = await request('/api/admin/dashboard'); renderDashboard(payload.dashboard); }
  function renderDashboard(data) {
    $('[data-dash-orders]').textContent = data.totalOrders; $('[data-dash-today]').textContent = `${data.todayOrders} transaksi hari ini`; $('[data-dash-revenue]').textContent = formatMoney(data.revenue); $('[data-dash-pending]').textContent = data.pendingOrders; $('[data-dash-average]').textContent = formatMoney(data.averageOrder); $('[data-dash-products]').textContent = `${data.totalProducts} produk · ${data.lowStock} stok menipis`;
    const chart = $('[data-sales-chart]'); const max = Math.max(...data.salesByDay.map((day) => day.revenue), 1);
    chart.replaceChildren(...data.salesByDay.map((day) => { const item = document.createElement('div'); item.className = 'chart__day'; const value = document.createElement('span'); value.className = 'chart__value'; value.textContent = day.revenue ? formatMoney(day.revenue).replace('Rp', 'Rp ') : `${day.orders} order`; const track = document.createElement('div'); track.className = 'chart__track'; const bar = document.createElement('i'); const bucket = Math.max(1, Math.ceil((day.revenue / max) * 10)); bar.className = `chart__bar h-${bucket}`; track.append(bar); const label = document.createElement('span'); label.className = 'chart__label'; label.textContent = new Intl.DateTimeFormat('id-ID', { weekday: 'short' }).format(new Date(`${day.date}T00:00:00Z`)); item.append(value, track, label); return item; }));
    const statusContainer = $('[data-status-overview]'); const maxStatus = Math.max(...Object.values(data.statusCounts), 1);
    statusContainer.replaceChildren(...Object.entries(data.statusCounts).map(([status, count]) => { const row = document.createElement('div'); row.className = 'status-line'; const label = document.createElement('span'); label.textContent = statusLabel(status); const strong = document.createElement('strong'); strong.textContent = count; const line = document.createElement('i'); line.className = `w-${Math.max(1, Math.ceil((count / maxStatus) * 10))}`; row.append(label, strong, line); return row; }));
    const recent = $('[data-recent-orders]'); recent.replaceChildren(...data.recentOrders.map((order) => createRecentOrder(order))); $('[data-recent-empty]').hidden = data.recentOrders.length > 0;
  }
  function createRecentOrder(order) { const row = document.createElement('article'); row.className = 'recent-order'; const identity = document.createElement('div'); const name = document.createElement('strong'); name.textContent = order.customer.name; const meta = document.createElement('small'); meta.textContent = `${order.id} · ${formatDate(order.createdAt)}`; identity.append(name, meta); const total = document.createElement('strong'); total.textContent = formatMoney(order.total); const status = createStatusBadge(order.status); row.append(identity, total, status); return row; }
  function createStatusBadge(status) { const badge = document.createElement('span'); badge.className = 'status-badge'; badge.dataset.status = status; badge.textContent = statusLabel(status); return badge; }

  async function loadOrders() {
    const payload = await request('/api/admin/orders'); state.orders = payload.orders; state.statuses = payload.statuses;
    const current = elements.orderFilter.value; elements.orderFilter.replaceChildren(new Option('Semua status', 'all'), ...state.statuses.map((status) => new Option(statusLabel(status), status))); elements.orderFilter.value = state.statuses.includes(current) ? current : 'all'; state.orderStatus = elements.orderFilter.value; renderOrders();
  }
  function filteredOrders() { const query = state.orderQuery.toLowerCase(); return state.orders.filter((order) => { const matchesStatus = state.orderStatus === 'all' || order.status === state.orderStatus; const text = `${order.id} ${order.customer.name} ${order.customer.whatsapp} ${order.customer.email || ''}`.toLowerCase(); return matchesStatus && text.includes(query); }); }
  function renderOrders() { const orders = filteredOrders(); elements.orderList.replaceChildren(...orders.map((order) => { const row = elements.orderTemplate.content.firstElementChild.cloneNode(true); row.querySelector('[data-order-id]').textContent = order.id; row.querySelector('[data-order-customer-name]').textContent = order.customer.name; row.querySelector('[data-order-date]').textContent = `${formatDate(order.createdAt)} · ${order.items.reduce((sum, item) => sum + item.quantity, 0)} item`; row.querySelector('[data-order-total]').textContent = formatMoney(order.total); const status = row.querySelector('[data-order-status]'); status.textContent = statusLabel(order.status); status.dataset.status = order.status; row.querySelector('[data-view-order]').addEventListener('click', () => openOrder(order.id)); return row; })); elements.orderCount.textContent = `${orders.length} dari ${state.orders.length} transaksi`; elements.orderEmpty.hidden = orders.length > 0; }
  function openOrder(id) { const order = state.orders.find((item) => item.id === id); if (!order) return; state.selectedOrderId = id; $('[data-order-dialog-id]').textContent = order.id; const customer = $('[data-order-customer]'); const details = [['Penerima', order.customer.name], ['WhatsApp', order.customer.whatsapp], ['Email', order.customer.email || '—'], ['Kota', order.customer.city], ['Alamat', order.customer.address], ['Pengiriman', order.shipping.name]]; customer.replaceChildren(...details.map(([labelText, valueText]) => { const div = document.createElement('div'); const label = document.createElement('span'); label.textContent = labelText; const value = document.createElement('strong'); value.textContent = valueText; div.append(label, value); return div; })); const items = $('[data-order-items]'); items.replaceChildren(...order.items.map((item) => { const row = document.createElement('div'); row.className = 'order-item'; const name = document.createElement('span'); name.textContent = `${item.name} · ${item.size} × ${item.quantity}`; const total = document.createElement('strong'); total.textContent = formatMoney(item.lineTotal); row.append(name, total); return row; })); const totals = $('[data-order-totals]'); totals.replaceChildren(...[['Subtotal', order.subtotal], ['Pengiriman', order.shipping.fee], ['Total', order.total]].map(([labelText, value]) => { const row = document.createElement('div'); const dt = document.createElement('dt'); dt.textContent = labelText; const dd = document.createElement('dd'); dd.textContent = formatMoney(value); row.append(dt, dd); return row; })); const history = $('[data-status-history]'); history.replaceChildren(...(order.statusHistory || [{ status: order.status, at: order.createdAt, by: 'system' }]).slice().reverse().map((entry) => { const row = document.createElement('div'); row.className = 'history-entry'; const dot = document.createElement('i'); const info = document.createElement('div'); const strong = document.createElement('strong'); strong.textContent = statusLabel(entry.status); const meta = document.createElement('span'); meta.textContent = `${entry.by || 'system'}${entry.note ? ` · ${entry.note}` : ''}`; info.append(strong, meta); const time = document.createElement('time'); time.textContent = formatDate(entry.at); row.append(dot, info, time); return row; })); const select = $('[data-order-status-select]'); select.replaceChildren(...state.statuses.map((status) => new Option(statusLabel(status), status))); select.value = order.status; elements.orderStatusForm.elements.note.value = ''; $('[data-order-message]').hidden = true; setDialog(true, elements.orderDialog); }
  async function updateOrderStatus(event) { event.preventDefault(); const form = new FormData(elements.orderStatusForm); const message = $('[data-order-message]'); message.hidden = true; try { const payload = await request(`/api/admin/orders/${state.selectedOrderId}`, { method: 'PATCH', body: JSON.stringify({ status: form.get('status'), note: form.get('note') }) }); state.orders = state.orders.map((order) => order.id === payload.order.id ? payload.order : order); renderOrders(); setDialog(false, elements.orderDialog); showToast('Status transaksi berhasil diperbarui.'); } catch (error) { message.textContent = error.message; message.hidden = false; } }

  async function loadProducts() { const payload = await request('/api/admin/products'); state.products = payload.products; renderProducts(); }
  function filteredProducts() { const query = state.productQuery.toLowerCase(); return state.products.filter((product) => `${product.id} ${product.nameId} ${product.nameEn} ${product.categoryId} ${product.categoryEn}`.toLowerCase().includes(query)); }
  function renderProductStats() { $('[data-stat-products]').textContent = state.products.length; $('[data-stat-stock]').textContent = state.products.reduce((sum, product) => sum + product.stock, 0).toLocaleString('id-ID'); $('[data-stat-low]').textContent = state.products.filter((product) => product.stock <= 5).length; $('[data-stat-featured]').textContent = state.products.filter((product) => product.featured).length; }
  function renderProducts() { const products = filteredProducts(); elements.productList.replaceChildren(...products.map((product) => { const card = elements.productTemplate.content.firstElementChild.cloneNode(true); const image = card.querySelector('img'); image.src = product.image; image.alt = product.nameId; card.querySelector('.admin-product__id').textContent = product.id; card.querySelector('h3').textContent = product.nameId; card.querySelector('.admin-product__identity p').textContent = `${product.categoryId} · ${product.sizes.join(', ')}`; card.querySelector('[data-product-price]').textContent = formatMoney(product.price); card.querySelector('[data-product-stock]').textContent = `${product.stock} unit`; card.querySelector('[data-edit-product]').addEventListener('click', () => openProductEditor(product)); card.querySelector('[data-delete-product]').addEventListener('click', () => deleteProduct(product)); return card; })); elements.productCount.textContent = `${products.length} dari ${state.products.length} produk`; elements.productEmpty.hidden = products.length > 0; renderProductStats(); }
  function productField(name) { return elements.productForm.elements.namedItem(name); }
  function openProductEditor(product = null) { state.editingProductId = product?.id || null; state.pendingImage = null; elements.productForm.reset(); elements.editorMessage.hidden = true; elements.editorTitle.textContent = product ? 'Edit produk' : 'Tambah produk'; const values = product || { nameId:'', nameEn:'', descriptionId:'', descriptionEn:'', category:'', categoryId:'', categoryEn:'', price:'', compareAtPrice:0, image:'/images/icon-apple.png', sizes:['All size'], stock:0, badgeId:'Baru', badgeEn:'New', featured:false }; ['nameId','nameEn','descriptionId','descriptionEn','category','categoryId','categoryEn','price','compareAtPrice','image','stock','badgeId','badgeEn'].forEach((name) => { productField(name).value = values[name] ?? ''; }); productField('sizes').value = Array.isArray(values.sizes) ? values.sizes.join(', ') : values.sizes; productField('featured').checked = Boolean(values.featured); elements.imagePreview.src = values.image || '/images/icon-apple.png'; setDialog(true, elements.editor); }
  function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error('Gambar tidak dapat dibaca.')); reader.readAsDataURL(file); }); }
  async function selectImage() { const file = elements.imageFile.files[0]; if (!file) return; if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { elements.editorMessage.textContent = 'Gunakan PNG, JPG, atau WebP maksimal 2 MB.'; elements.editorMessage.hidden = false; return; } const dataUrl = await readFile(file); state.pendingImage = { name:file.name, mimeType:file.type, data:dataUrl.split(',')[1] }; elements.imagePreview.src = dataUrl; }
  async function saveProduct(event) { event.preventDefault(); const button = $('[data-save-product]'), original = button.textContent; button.disabled = true; button.textContent = 'Menyimpan...'; elements.editorMessage.hidden = true; try { if (state.pendingImage) { const upload = await request('/api/admin/images', { method:'POST', body:JSON.stringify(state.pendingImage) }); productField('image').value = upload.image; } const product = { nameId:productField('nameId').value, nameEn:productField('nameEn').value, descriptionId:productField('descriptionId').value, descriptionEn:productField('descriptionEn').value, category:productField('category').value, categoryId:productField('categoryId').value, categoryEn:productField('categoryEn').value, price:Number(productField('price').value), compareAtPrice:Number(productField('compareAtPrice').value || 0), image:productField('image').value, sizes:productField('sizes').value.split(',').map((size) => size.trim()).filter(Boolean), stock:Number(productField('stock').value), badgeId:productField('badgeId').value, badgeEn:productField('badgeEn').value, featured:productField('featured').checked }; const editing = Boolean(state.editingProductId); const payload = await request(editing ? `/api/admin/products/${state.editingProductId}` : '/api/admin/products', { method:editing ? 'PUT':'POST', body:JSON.stringify(product) }); if (editing) state.products = state.products.map((item) => item.id === payload.product.id ? payload.product : item); else state.products.unshift(payload.product); renderProducts(); setDialog(false, elements.editor); showToast(editing ? 'Produk berhasil diperbarui.' : 'Produk berhasil ditambahkan.'); } catch (error) { elements.editorMessage.textContent = error.message; elements.editorMessage.hidden = false; } finally { button.disabled = false; button.textContent = original; } }
  async function deleteProduct(product) { if (!window.confirm(`Hapus “${product.nameId}” dari katalog?`)) return; try { await request(`/api/admin/products/${product.id}`, { method:'DELETE' }); state.products = state.products.filter((item) => item.id !== product.id); renderProducts(); showToast('Produk berhasil dihapus.'); } catch (error) { showToast(error.message); } }

  async function loadUsers() { const payload = await request('/api/admin/users'); state.users = payload.users; renderUsers(); }
  function filteredUsers() { const query = state.userQuery.toLowerCase(); return state.users.filter((user) => `${user.name} ${user.username} ${user.role}`.toLowerCase().includes(query)); }
  function renderUsers() { const users = filteredUsers(); elements.userList.replaceChildren(...users.map((user) => { const row = elements.userTemplate.content.firstElementChild.cloneNode(true); row.querySelector('[data-user-avatar]').textContent = (user.name || user.username).slice(0,1).toUpperCase(); row.querySelector('[data-user-name]').textContent = user.name || user.username; row.querySelector('[data-user-username]').textContent = `@${user.username}${user.virtual ? ' · environment' : ''}`; row.querySelector('[data-user-role]').textContent = user.role; const active = row.querySelector('[data-user-state]'); active.textContent = user.active ? 'Aktif' : 'Nonaktif'; active.classList.toggle('is-inactive', !user.active); const edit = row.querySelector('[data-edit-user]'), remove = row.querySelector('[data-delete-user]'); edit.disabled = Boolean(user.virtual); remove.disabled = Boolean(user.virtual) || user.id === state.currentUser.id; edit.addEventListener('click', () => openUserEditor(user)); remove.addEventListener('click', () => deleteUser(user)); return row; })); elements.userCount.textContent = `${users.length} dari ${state.users.length} pengguna`; elements.userEmpty.hidden = users.length > 0; }
  function userField(name) { return elements.userForm.elements.namedItem(name); }
  function openUserEditor(user = null) { if (user?.virtual) return; state.editingUserId = user?.id || null; elements.userForm.reset(); elements.userMessage.hidden = true; $('[data-user-dialog-title]').textContent = user ? 'Edit pengguna' : 'Tambah pengguna'; userField('name').value = user?.name || ''; userField('username').value = user?.username || ''; userField('username').disabled = Boolean(user); userField('role').value = user?.role || 'editor'; userField('active').checked = user ? user.active : true; userField('password').required = !user; $('[data-user-password-hint]').textContent = user ? '(kosongkan jika tidak diubah)' : 'minimal 10 karakter'; const ownerOption = userField('role').querySelector('option[value="owner"]'); ownerOption.disabled = state.currentUser.role !== 'owner'; setDialog(true, elements.userDialog); }
  async function saveUser(event) { event.preventDefault(); elements.userMessage.hidden = true; const editing = Boolean(state.editingUserId); const user = { name:userField('name').value, username:userField('username').value, role:userField('role').value, password:userField('password').value, active:userField('active').checked }; try { const payload = await request(editing ? `/api/admin/users/${state.editingUserId}` : '/api/admin/users', { method:editing ? 'PUT':'POST', body:JSON.stringify(user) }); if (editing) state.users = state.users.map((item) => item.id === payload.user.id ? payload.user : item); else state.users.push(payload.user); renderUsers(); setDialog(false, elements.userDialog); showToast(editing ? 'Pengguna berhasil diperbarui.' : 'Pengguna berhasil ditambahkan.'); } catch (error) { elements.userMessage.textContent = error.message; elements.userMessage.hidden = false; } }
  async function deleteUser(user) { if (!window.confirm(`Hapus akses CMS untuk “${user.name || user.username}”?`)) return; try { await request(`/api/admin/users/${user.id}`, { method:'DELETE' }); state.users = state.users.filter((item) => item.id !== user.id); renderUsers(); showToast('Pengguna berhasil dihapus.'); } catch (error) { showToast(error.message); } }

  let toastTimer; function showToast(message) { clearTimeout(toastTimer); elements.toast.textContent = message; elements.toast.hidden = false; toastTimer = setTimeout(() => { elements.toast.hidden = true; }, 3000); }
  async function login(event) { event.preventDefault(); const button = $('[data-login-submit]'), data = new FormData(elements.loginForm); button.disabled = true; button.textContent = 'Memeriksa...'; elements.loginMessage.hidden = true; try { const payload = await request('/api/admin/login', { method:'POST', body:JSON.stringify({ username:data.get('username'), password:data.get('password') }) }); state.csrfToken = payload.csrfToken; elements.loginForm.reset(); showDashboard(payload.user); await switchView('dashboard'); } catch (error) { showLogin(error.message); } finally { button.disabled = false; button.textContent = 'Masuk'; } }
  async function logout() { try { await request('/api/admin/logout', { method:'POST' }); } catch { /* sesi boleh sudah berakhir */ } showLogin('Anda sudah keluar dari CMS.'); }

  function bindEvents() {
    elements.loginForm.addEventListener('submit', login); $('[data-logout]').addEventListener('click', logout);
    document.querySelectorAll('[data-view-button]').forEach((button) => button.addEventListener('click', () => switchView(button.dataset.viewButton).catch((error) => showToast(error.message))));
    $('[data-refresh-dashboard]').addEventListener('click', () => loadDashboard().catch((error) => showToast(error.message))); $('[data-go-orders]').addEventListener('click', () => switchView('orders'));
    elements.orderSearch.addEventListener('input', (event) => { state.orderQuery = event.target.value.trim(); renderOrders(); }); elements.orderFilter.addEventListener('change', (event) => { state.orderStatus = event.target.value; renderOrders(); }); elements.orderStatusForm.addEventListener('submit', updateOrderStatus); $('[data-close-order]').addEventListener('click', () => setDialog(false, elements.orderDialog)); elements.orderDialog.addEventListener('click', (event) => { if (event.target === elements.orderDialog) setDialog(false, elements.orderDialog); });
    $('[data-add-product]').addEventListener('click', () => openProductEditor()); $('[data-close-editor]').addEventListener('click', () => setDialog(false, elements.editor)); $('[data-cancel-editor]').addEventListener('click', () => setDialog(false, elements.editor)); elements.editor.addEventListener('click', (event) => { if (event.target === elements.editor) setDialog(false, elements.editor); }); elements.productForm.addEventListener('submit', saveProduct); elements.imageFile.addEventListener('change', selectImage); productField('image').addEventListener('input', () => { if (!state.pendingImage) elements.imagePreview.src = productField('image').value || '/images/icon-apple.png'; }); elements.productSearch.addEventListener('input', (event) => { state.productQuery = event.target.value.trim(); renderProducts(); });
    $('[data-add-user]').addEventListener('click', () => openUserEditor()); $('[data-close-user]').addEventListener('click', () => setDialog(false, elements.userDialog)); $('[data-cancel-user]').addEventListener('click', () => setDialog(false, elements.userDialog)); elements.userDialog.addEventListener('click', (event) => { if (event.target === elements.userDialog) setDialog(false, elements.userDialog); }); elements.userForm.addEventListener('submit', saveUser); elements.userSearch.addEventListener('input', (event) => { state.userQuery = event.target.value.trim(); renderUsers(); });
  }

  async function init() { bindEvents(); try { const session = await request('/api/admin/session'); state.csrfToken = session.csrfToken; showDashboard(session.user); await switchView('dashboard'); } catch (error) { showLogin(error.status === 503 ? error.message : ''); } }
  init();
})();
